### ISSUE TITLE
error compile IRcontrol

### ISSUE THREAD

**Issue by Xav83130** [jasoncoon/esp8266-fastled-webserver#33]
Hello,
I have error when i compile on ESP8266 NodeMCU 1.0
If you have an idea of the problem I am taker ; )

sp8266-fastled-webserver:43: error: 'IRrecv' does not name a type
 IRrecv irReceiver(RECV_PIN);
 ^
In file included from /Users/xaviergesset/Desktop/DESIGNtree - Project/Arduino/esp8266-fastled-webserver-1.1/esp8266-fastled-webserver/esp8266-fastled-webserver.ino:45:0:
sketch/Commands.h: In function 'long unsigned int decodeIRCode()':
Commands.h:179: error: 'decode_results' was not declared in this scope
   decode_results results;
   ^
Commands.h:179: error: expected ';' before 'results'
   decode_results results;
                  ^
Commands.h:181: error: 'results' was not declared in this scope
   results.value = 0;
   ^
Commands.h:184: error: 'irReceiver' was not declared in this scope
   if (irReceiver.decode(&results)) {
       ^
/Users/------------/Desktop/---------- - Project/Arduino/esp8266-fastled-webserver-1.1/esp8266-fastled-webserver/esp8266-fastled-webserver.ino: In function 'void setup()':
esp8266-fastled-webserver:231: error: 'irReceiver' was not declared in this scope
   irReceiver.enableIRIn(); // Start the receiver
   ^
exit status 1
'IRrecv' does not name a type

Other little question, 
Is it possible not to use IRcontrol?

thank you in advance
And thanks for sharing

**Comment by matthewjporter** [comment]
I resolved this by following the correct library upload instruction here: https://github.com/sebastienwarin/IRremoteESP8266

**Comment by Xav83130** [comment]
Thanks it's good
